### ISSUE TITLE
Add a setup.py

### ISSUE THREAD

**Issue by Painadath** [Pythonic456/Fedit#1]
i am interested to make your project wonderfull i will make a setup.py
which will do

*make the project available through commandline and desktop menu
without affecting the current project.if you are interetsted post a reply

PS(IT WILL WORK ONLY WITH LINUX)

**Comment by Pythonic456** [comment]
Yes I would like a setup script, and the main target OS is Linux anyway.
Thank you!

**Comment by Painadath** [comment]
Yep I will work on it tomorrow and  make a Pr

**Comment by Painadath** [comment]
So it need a lcon to desktop menu could you please handle me a link containing it

**Comment by Pythonic456** [comment]
You can use either the SVG or the PNG, they are both in the root directory of this repository.

**Comment by Painadath** [comment]
Because of the heavy rain .I just started the setup.py I will on it more on tommorow

**Comment by Pythonic456** [comment]
👍

**Comment by Painadath** [comment]
Hey i have made a pr before merging it please download and test my fork of this repo and after if there is no problem you can merge the PulRequest

**Comment by Painadath** [comment]
I will open a new pr now more detailes on closed pr

**Comment by Pythonic456** [comment]
A few things I need to change, then I will close this issue.

**Comment by Painadath** [comment]
@Pythonic456 you have to change the setup.py inorder to remanming fedit.py to main.py
and desktop entry please edit it

**Comment by Pythonic456** [comment]
Ok, all done. Please test it and let me know how it goes 👍

**Comment by Painadath** [comment]
Ok tested its completelty working you may now close this issue

**Comment by Pythonic456** [comment]
Ok, thanks for the help!
