### ISSUE TITLE
More features

### ISSUE THREAD

**Issue by Painadath** [Pythonic456/Fedit#4]
I would like to have some features with fedit
*at the bottom show howmany characters typed
*give buttons a different color instead of theme and make it highlight on any theme 
*and will inform more

**Comment by Painadath** [comment]
OH first rewrite the README and notes!!!

**Comment by Painadath** [comment]
and make the prefrence window to close when main window closed.

**Comment by Painadath** [comment]
and remove the data folder

**Comment by Pythonic456** [comment]
So these are the features you want:

- Show how many characters typed
- Rewrite README.md and notes.txt
- Close all windows when main window closed

I don't understand what you mean by these:
> give buttons a different color instead of theme and make it highlight on any theme
> and remove the data folder

Can you explain these please?

**Comment by Painadath** [comment]
I meant to highlight the color of button in any theme and to show the number of character s

**Comment by Pythonic456** [comment]
So that the buttons are the opposite of the theme?
If I am missing something please attempt an illustration of what you mean.
Thanks 👍

**Comment by Painadath** [comment]
https://www.webdesignerdepot.com/cdn-origin/uploads/2008/11/02_fckeditor.jpg
As you can see the buttons are highlighted with repect to the editing space

**Comment by Pythonic456** [comment]
"Highlighted"? Do you mean the inapplicable ones are greyed out?
I am pretty sure I am missing something here.

**Comment by Painadath** [comment]
I meant that the buttons must have a different color according to the theme

**Comment by Pythonic456** [comment]
Does it not do this already?
![Fedit (0 0 1 5) 12_04_2021 15_43_53](https://user-images.githubusercontent.com/56113118/114413663-18548200-9ba6-11eb-9bd1-3e074fd25a4a.png)
![Fedit (0 0 1 5) 12_04_2021 15_44_00](https://user-images.githubusercontent.com/56113118/114413672-1ab6dc00-9ba6-11eb-859e-4af9b01fa458.png)
The buttons do change colour as well. Do you mean a _different_ colour than the theme?

**Comment by Painadath** [comment]
Ya and It must me different than the background color
Like this
Black background=grey button background

**Comment by Pythonic456** [comment]
Oh okay, so they stand out from the window more?

**Comment by Painadath** [comment]
ya 
and this is a very difficult but i am asking if you have time do it
make the key words in each language on sperate color
``` python
for i in range
```

**Comment by Painadath** [comment]
may be this could help 
https://www.geeksforgeeks.org/change-the-color-of-certain-words-in-the-tkinter-text-widget/

**Comment by Pythonic456** [comment]
Yeah, I have tried doing keyword highlighting before, and yes, it is quite involved.

I don't think Fedit is at the point where it needs highlighting, but when I think it is ready for that, I will
make a new issue to discuss this point further.

These ones will be done soon.
- Show how many characters typed
- Rewrite README.md and notes.txt
- Close all windows when main window closed

**Comment by Pythonic456** [comment]
@Painadath Check the commit description.

**Comment by Painadath** [comment]
Will check it out I am currently working on some project with https://github.com/zachthecoder14
We are working on a coding service site

**Comment by Pythonic456** [comment]
@Painadath These features you requested have been added/done:

- Character count
- Different button colour
- README.md rewritten and notes.txt deleted

**Comment by Painadath** [comment]
Ok
And also can you help us in pi-ware development 
Here is the GitHub repo please join in the discord server https://github.com/zachthecoder14/pi-ware

**Comment by Painadath** [comment]
So can I close this

**Comment by Pythonic456** [comment]
Yes, I suppose so.
